export const fontCollection = [
  { name: "宋体", value: "SimSun" },
  { name: "黑体", value: "SimHei" },
  { name: "微软雅黑", value: "Microsoft Yahei" },
  { name: "微软正黑体", value: "Microsoft JhengHei" },
  { name: "楷体", value: "KaiTi" },
  { name: "新宋体", value: "NSimSun" },
  { name: "仿宋", value: "FangSong" },
  { name: "苹方", value: "PingFang SC" },
  { name: "幼圆", value: "YouYuan" },
  { name: "隶书", value: "LiSu" },
  { name: "华文细黑", value: "STXihei" },
  { name: "华文黑体", value: "STHeiti" },
  { name: "华文楷体", value: "STKaiti" },
  { name: "华文宋体", value: "STSong" },
  { name: "华文仿宋", value: "STFangsong" },
  { name: "华文中宋", value: "STZhongsong" },
  { name: "华文琥珀", value: "STHupo" },
  { name: "华文新魏", value: "STXinwei" },
  { name: "华文隶书", value: "STLiti" },
  { name: "华文行楷", value: "STXingkai" },
  { name: "方正舒体", value: "FZShuTi" },
  { name: "方正姚体", value: "FZYaoti" },
  { name: "冬青黑体简", value: "Hiragino Sans GB" },
  { name: "兰亭黑-简", value: "Lantinghei SC" },
  { name: "翩翩体-简", value: "Hanzipen SC" },
  { name: "手札体-简", value: "Hannotate SC" },
  { name: "宋体-简", value: "Songti SC" },
  { name: "娃娃体-简", value: "Wawati SC" },
  { name: "魏碑-简", value: "Weibei SC" },
  { name: "行楷-简", value: "Xingkai SC" },
  { name: "雅痞-简", value: "Yapi SC" },
  { name: "圆体-简", value: "Yuanti SC" },
];
